apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-deployment
  labels:
    app: notejam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: imohitbhatt/notejam:4.0
        ports:
        - containerPort: 8000
