apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: notejam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
        - name: notejam
          image: imohitbhatt/notejam:4.0
          ports:
            - containerPort: 8000

        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: notejam-pv-volume

      volumes:
      - name: notejam-pv-volume
        persistentVolumeClaim:
          claimName: notejam-pv-claim
